# -*- coding: utf-8 -*-
import sys

import cv2
import numpy as np
import torch
from PIL import Image
# Form implementation generated from reading ui file 'face_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1350, 880)
        Form.setMinimumSize(QtCore.QSize(1200, 760))
        Form.setStyleSheet("""
            QWidget {
                font-family: 'Microsoft YaHei', 'PingFang SC', 'Segoe UI', sans-serif;
                font-size: 12px;
                color: #1f2937;
                background-color: #f5f7fb;
            }
            QGroupBox {
                background: #ffffff;
                border: 1px solid #e5e7eb;
                border-radius: 14px;
                margin-top: 14px;
                padding: 12px;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                subcontrol-position: top left;
                padding: 0 8px;
                margin-left: 10px;
                color: #111827;
                font-weight: 600;
            }
            QLabel {
                background: transparent;
            }
            QLabel#label {
                font-size: 24px;
                font-weight: 700;
                color: #0f172a;
                padding: 6px 0 14px 0;
            }
            QLabel#label_2, QLabel#label_3, QLabel#label_9 {
                border: 1px dashed #cbd5e1;
                border-radius: 12px;
                background: #f8fafc;
                color: #64748b;
                min-height: 220px;
            }
            QPushButton {
                border: none;
                border-radius: 10px;
                padding: 8px 14px;
                background: #2563eb;
                color: white;
                font-weight: 600;
            }
            QPushButton:hover {
                background: #1d4ed8;
            }
            QPushButton:pressed {
                background: #1e40af;
            }
            QLineEdit, QTextBrowser, QTableWidget {
                border: 1px solid #dbe3ee;
                border-radius: 10px;
                background: #ffffff;
                selection-background-color: #93c5fd;
            }
            QLineEdit {
                padding: 8px 10px;
            }
            QTextBrowser {
                padding: 10px;
            }
            QRadioButton {
                spacing: 8px;
                color: #374151;
            }
            QRadioButton::indicator {
                width: 16px;
                height: 16px;
            }
            QTabWidget::pane {
                border: 0;
            }
            QTableWidget {
                gridline-color: #e5e7eb;
            }
            QHeaderView::section {
                background: #eff6ff;
                color: #1e3a8a;
                padding: 8px;
                border: none;
                font-weight: 600;
            }
        """)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setContentsMargins(18, 18, 18, 18)
        self.horizontalLayout_2.setSpacing(18)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(14)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_14.setMinimumSize(QtCore.QSize(0, 42))
        self.pushButton_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_11.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_15.setMinimumSize(QtCore.QSize(0, 42))
        self.pushButton_15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_11.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_16.setMinimumSize(QtCore.QSize(0, 42))
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_11.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_17.setMinimumSize(QtCore.QSize(0, 42))
        self.pushButton_17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_11.addWidget(self.pushButton_17)
        self.verticalLayout_2.addLayout(self.verticalLayout_11)
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.page1)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setMinimumHeight(38)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setMinimumHeight(38)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setMinimumHeight(38)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_6.addWidget(self.pushButton_8)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_7.setMinimumHeight(38)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_6.addWidget(self.pushButton_7)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setMinimumHeight(38)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.horizontalLayout_6.setStretch(0, 3)
        self.horizontalLayout_6.setStretch(1, 1)
        self.horizontalLayout_6.setStretch(2, 1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_3.setStretch(0, 3)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_12.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.addWidget(self.groupBox_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page1)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_9.setSpacing(40)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_11.addWidget(self.lineEdit_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton.setChecked(True)
        self.radioButton.setAutoRepeat(False)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_8.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_8.addWidget(self.radioButton_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_10.addWidget(self.lineEdit_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_9.addWidget(self.lineEdit_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_9.setMinimumHeight(42)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_7.addWidget(self.pushButton_9)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3.setStretch(7, 3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.page2)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_8 = QtWidgets.QGroupBox(self.page2)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_9 = QtWidgets.QLabel(self.groupBox_8)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_20.addWidget(self.label_9)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_22.setMinimumHeight(38)
        self.pushButton_22.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_17.addWidget(self.pushButton_22)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_6.setMinimumHeight(38)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_17.addWidget(self.lineEdit_6)
        self.verticalLayout_21.addLayout(self.horizontalLayout_17)
        self.verticalLayout_20.addWidget(self.groupBox_11)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_23.setMinimumHeight(38)
        self.pushButton_23.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_19.addWidget(self.pushButton_23)
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_25.setMinimumHeight(38)
        self.pushButton_25.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_19.addWidget(self.pushButton_25)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_19)
        self.verticalLayout_20.addWidget(self.groupBox_12)
        self.verticalLayout_20.setStretch(0, 3)
        self.verticalLayout_20.setStretch(1, 1)
        self.verticalLayout_20.setStretch(2, 1)
        self.verticalLayout_19.addLayout(self.verticalLayout_20)
        self.verticalLayout_14.addWidget(self.groupBox_8)
        self.horizontalLayout_12.addLayout(self.verticalLayout_14)
        self.groupBox_7 = QtWidgets.QGroupBox(self.page2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_7)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_15.addWidget(self.textBrowser)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem)
        self.verticalLayout_15.setStretch(0, 8)
        self.verticalLayout_15.setStretch(1, 1)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        self.horizontalLayout_12.addWidget(self.groupBox_7)
        self.horizontalLayout_12.setStretch(0, 6)
        self.horizontalLayout_12.setStretch(1, 4)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_12)
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.page3)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(25)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.page3)
        self.lineEdit_5.setMinimumHeight(38)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_14.addWidget(self.lineEdit_5)
        self.pushButton_2 = QtWidgets.QPushButton(self.page3)
        self.pushButton_2.setMinimumHeight(38)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_14.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.page3)
        self.pushButton_3.setMinimumHeight(38)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_14.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.page3)
        self.pushButton_4.setMinimumHeight(38)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_14.addWidget(self.pushButton_4)
        self.horizontalLayout_14.setStretch(0, 3)
        self.horizontalLayout_14.setStretch(1, 1)
        self.horizontalLayout_14.setStretch(2, 1)
        self.horizontalLayout_14.setStretch(3, 1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_14)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)
        self.tableWidget = QtWidgets.QTableWidget(self.page3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_18.addWidget(self.tableWidget)
        self.stackedWidget.addWidget(self.page3)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 9)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "人脸识别系统"))
        self.groupBox_5.setTitle(_translate("Form", "功能选项"))
        self.pushButton_14.setText(_translate("Form", "人脸信息录入"))
        self.pushButton_15.setText(_translate("Form", "人脸识别"))
        self.pushButton_16.setText(_translate("Form", "数据库管理"))
        self.pushButton_17.setText(_translate("Form", "退出"))
        self.groupBox_6.setTitle(_translate("Form", "相机设置"))
        self.label_2.setText(_translate("Form", "等待图像输入"))
        self.groupBox.setTitle(_translate("Form", "方式一：图片"))
        self.pushButton_5.setText(_translate("Form", "上传图片"))
        self.groupBox_2.setTitle(_translate("Form", "方式二：摄像头"))
        self.pushButton_8.setText(_translate("Form", "打开摄像头"))
        self.pushButton_7.setText(_translate("Form", "拍照"))
        self.pushButton_6.setText(_translate("Form", "关闭摄像头"))
        self.groupBox_3.setTitle(_translate("Form", "人脸信息"))
        self.label_3.setText(_translate("Form", "显示头像"))
        self.label_5.setText(_translate("Form", "姓名"))
        self.label_7.setText(_translate("Form", "性别"))
        self.radioButton.setText(_translate("Form", "男"))
        self.radioButton_2.setText(_translate("Form", "女"))
        self.label_6.setText(_translate("Form", "年龄"))
        self.label_4.setText(_translate("Form", "学号"))
        self.pushButton_9.setText(_translate("Form", "保存设置"))
        self.groupBox_8.setTitle(_translate("Form", "相机设置"))
        self.label_9.setText(_translate("Form", "等待图像输入"))
        self.groupBox_11.setTitle(_translate("Form", "方式一：图片"))
        self.pushButton_22.setText(_translate("Form", "上传图片"))
        self.groupBox_12.setTitle(_translate("Form", "方式二：摄像头"))
        self.pushButton_23.setText(_translate("Form", "打开摄像头"))
        self.pushButton_25.setText(_translate("Form", "关闭摄像头"))
        self.groupBox_7.setTitle(_translate("Form", "识别结果"))
        self.lineEdit_5.setPlaceholderText(_translate("Form", "请输入你的名字"))
        self.pushButton_2.setText(_translate("Form", "查询"))
        self.pushButton_3.setText(_translate("Form", "删除"))
        self.pushButton_4.setText(_translate("Form", "刷新"))



